[build]
command = "npm install && npm run build"

[deploy]
startCommand = "npm start"

[env]
NODE_ENV = "production"
PORT = "3000"
REACT_APP_SERVER_URL = "https://teamsphere-server-production.up.railway.app/v1/"
